version: "3.3"

services:
  userapi:
    image: "symplesims/userapi:latest"
    container_name: userapi
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    restart: always
    volumes:
      - shared-volume:/var/log/myapp
  fluent-bit:
    image: "symplesims/aws-for-fluent-bit:local"
    #command: bash -c "sleep 3600;"
    container_name: fluentbit
    environment:
      - "ECS_CLUSTER_NAME=symple-as1d-demo-ecs"
      - "ECS_AWS_REGION=ap-northeast-1"
      - "ECS_APP_NAME=userapi"
      - "LOG_FILEPATH=/var/log/myapp/app.log"
    volumes:
      - shared-volume:/var/log/myapp
      - /tmp/lima/myapp:/tmp
    depends_on:
      - userapi

# Building Image for Deploy
volumes:
  shared-volume:


# docker-compose -f ./cicd/local/docker-compose.yaml up
# docker-compose -f ./cicd/local/docker-compose.yaml down
# docker container ls
